-- Create claims table for gift claims and contributions
create table public.claims (
  id bigint generated by default as identity primary key,
  item_id text not null,
  item_name text not null,
  guest_name text not null,
  guest_email text,
  claim_type text not null, -- 'claim' or 'contribution'
  amount numeric, -- only for contributions
  message text,
  status text default 'pending', -- 'pending', 'confirmed', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.claims enable row level security;

-- Allow anonymous inserts (for claim/contribution form submissions)
create policy "Allow anonymous inserts" on public.claims
  for insert
  with check (true);

-- Allow anonymous reads (optional - if you want to display claims publicly)
create policy "Allow anonymous reads" on public.claims
  for select
  using (true);
