-- Create rsvps table for wedding RSVPs
create table public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  attending text not null, -- 'yes' or 'no'
  events text[], -- array of event names (e.g., ['Ceremony', 'Reception'])
  message text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.rsvps enable row level security;

-- Allow anonymous inserts (for RSVP form submissions)
create policy "Allow anonymous inserts" on public.rsvps
  for insert
  with check (true);

-- Allow anonymous reads (optional - if you want to display RSVP count publicly)
create policy "Allow anonymous reads" on public.rsvps
  for select
  using (true);
